import NavBar from "../components/NavBar";
import GlobalContextProvider from "../GlobalContext";
import "./globals.css";
import "@near-wallet-selector/modal-ui/styles.css";

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <head>
        <title>Cantoverse - The metaverse platform dedicated to Edtech</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </head>
      <body className="flex flex-col flex-1 bg-gray-50">
        <GlobalContextProvider>
          <NavBar />
          <main className="h-full">{children}</main>
        </GlobalContextProvider>
      </body>
    </html>
  );
}
